In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\guest\Documents\CsixDataset\insurance.csv", sep=';')
df.head()

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190

In [2]:
df = df.convert_dtypes()

In [3]:
df.head()

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,<NA>,190
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,<NA>,190
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,<NA>,190
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,<NA>,190
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,<NA>,190

In [4]:
df.dtypes

ID                               Int64
Date_start_contract     string[python]
Date_last_renewal       string[python]
Date_next_renewal       string[python]
Date_birth              string[python]
Date_driving_licence    string[python]
Distribution_channel             Int64
Seniority                        Int64
Policies_in_force                Int64
Max_policies                     Int64
Max_products                     Int64
Lapse                            Int64
Date_lapse              string[python]
Payment                          Int64
Premium                        Float64
Cost_claims_year               Float64
N_claims_year                    Int64
N_claims_history                 Int64
R_Claims_history               Float64
Type_risk                        Int64
Area                             Int64
Second_driver                    Int64
Year_matriculation               Int64
Power                            Int64
Cylinder_capacity                Int64
Value_vehicle                  Float64
N_doors                          Int64
Type_fuel               string[python]
Length                         Float64
Weight                           Int64
dtype: object

In [15]:
df.to_csv('isurance_dash.csv', index=False)

In [17]:
df.describe(Date_start_contract)

NameError: name 'Date_start_contract' is not defined